# Generated by Django 5.1.7 on 2025-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='washcount',
            field=models.IntegerField(default=0),
        ),
    ]
