# Generated by Django 5.1.7 on 2025-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_washcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='إسم العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vehicle_plate',
            field=models.CharField(max_length=10, verbose_name='رقم لوحة السيارة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='washcount',
            field=models.IntegerField(default=0, verbose_name='عدد الغسلات'),
        ),
    ]
